name: 4D-humans
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy<=1.23.1
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - pip
  - pip:
    - pytorch-lightning
    - smplx==0.1.28
    - pyrender
    - opencv-python
    - yacs
    - scikit-image
    - einops
    - timm
    - dill
    - chumpy
    - git+https://github.com/facebookresearch/detectron2

    # For training
    - rich
    - hydra-core
    - hydra-submitit-launcher
    - hydra-colorlog
    - pyrootutils
    - webdataset
